source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import login_view, UserLogoutView
from main import settings
from webapp.views import IndexView, TaskView, CreateTaskView, EditTaskView, DeleteTaskView, StatusAddView, TypeAddView, \
    EditStatusView, DeleteStatusView, EditTypeView, DeleteTypeView, ProjectsView, ProjectView, ProjectCreateView, \
    ProjectEditView, ProjectDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import TaskView, CreateTaskView, EditTaskView, IndexView, DeleteTaskView, StatusAddView, \
    EditStatusView, DeleteStatusView, TypeAddView, EditTypeView, DeleteTypeView, ProjectsView, ProjectView, \
    ProjectCreateView, ProjectEditView, ProjectDeleteView

urlpatterns = [
    path('', IndexView.as_view(), name='main_page'),
    path('task/<int:pk>/', TaskView.as_view(), name='view task'),
    path('project/<int:pk>/task/create/', CreateTaskView.as_view(), name='create task'),
    path('task/<int:pk>/edit/', EditTaskView.as_view(), name='edit task'),
    path('task/<int:pk>/delete/', DeleteTaskView.as_view(), name='delete task'),

    path('status/add/', StatusAddView.as_view(), name='add status'),
    path('status/<int:pk>/edit/', EditStatusView.as_view(), name='edit status'),
    path('status/<int:pk>/delete/', DeleteStatusView.as_view(), name='delete status'),

    path('types/add/', TypeAddView.as_view(), name='add type'),
    path('types/<int:pk>/edit/', EditTypeView.as_view(), name='edit type'),
    path('types/<int:pk>/delete/', DeleteTypeView.as_view(), name='delete type'),

    path('projects/', ProjectsView.as_view(), name='view projects'),
    path('project/<int:pk>/', ProjectView.as_view(), name='view project'),
    path('project/create/', ProjectCreateView.as_view(), name='create project'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='edit project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete project'),
]

app_name='webapp'

source/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class GitHubRepo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='profile')
    avatar = models.ImageField(null=True, blank=True,  verbose_name='Аватар', upload_to='user_pics')
    description = models.TextField(max_length=1000, null=True, blank=True, verbose_name='О себе')
    repo_url = models.URLField(verbose_name='github repo url')

    def __str__(self):
        return self.user.get_full_name() + "'s profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'


class Team(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team',verbose_name='Участник команды')
    project = models.ForeignKey('webapp.Project', on_delete=models.PROTECT, related_name='team', verbose_name='Проект команды')
    starting_date = models.DateField(verbose_name='Дата начала работы', null=False, blank=False)
    end_date = models.DateField(verbose_name='Дата окончания работы', null=True, blank=True)

    def __str__(self):
        return "Участник {} проекта '{}'".format(self.user, self.project)

source/webapp/models.py
from django.contrib.auth.models import User
from django.db import models

PROJECT_STATUS_DEFAULT = 'active'
PROJECT_STATUSES=[(PROJECT_STATUS_DEFAULT, 'Активный'),('closed','Закрыт')]

def assign_author():
    super_author = User.objects.get(username='ernest_aitiev')
    return super_author.id


class Task(models.Model):
    summary = models.CharField(max_length=200, null=False, blank=False, verbose_name='summary')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='description')
    status = models.ForeignKey('webapp.Status', on_delete=models.PROTECT,related_name='tasks', verbose_name='status',
                               null=True, blank=True)
    type = models.ForeignKey('webapp.Type',on_delete=models.PROTECT, related_name='tasks', verbose_name='type',
                             null=True, blank=True)
    created_at= models.DateTimeField(auto_now_add=True, verbose_name='created')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Время изменения')
    project = models.ForeignKey('webapp.Project', on_delete=models.CASCADE, related_name='tasks', verbose_name='projects', null=True, blank=False)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='tasks_created', default=assign_author, verbose_name='author', null=True, blank=False)
    assigned_to = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks_assigned', verbose_name='executor', null=True, blank=True)


    def __str__(self):
        return self.summary


class Type(models.Model):
    name = models.CharField(max_length=15, verbose_name='task_name')

    def __str__(self):
        return self.name


class Status(models.Model):
    name = models.CharField(max_length=15, verbose_name='status_name')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name='Status'
        verbose_name_plural='Status'


class Project(models.Model):
    name = models.CharField(max_length=100, null=True, blank=False, verbose_name='project_name')
    description = models.TextField(max_length=2000, null=True, blank=True, verbose_name='project_description')
    created_at= models.DateTimeField(auto_now_add=True, verbose_name='project_created')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='project_updated')
    status = models.CharField(choices=PROJECT_STATUSES, max_length=10, default=PROJECT_STATUS_DEFAULT, verbose_name='Статус проекта')
    squad = models.ManyToManyField(User, through='accounts.Team', through_fields=('project','user'),related_name='projects', blank=True )


    def __str__(self):
        return self.name

source/webapp/views/baseclass.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView


class DetailView(TemplateView):
    context_key = 'object'
    model = None

    def get_object(self, pk):
        try:
            some_object = self.model.objects.get(pk=pk)
        except self.model.DoesNotExist:
            raise Http404('НЕТ ТАКОГО ОБЪЕКТА!')
        return some_object

    def get_context_data(self, **kwargs):
        pk = kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object(pk=pk)
        return context


class UpdateView(TemplateView):
    model = None
    form_class = None
    template_name = None
    redirect_url = None
    object = None
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        form = self.form_class(instance=self.object)
        return render(request, self.template_name, context={'form': form, self.context_key: self.object})

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        return render(self.request, self.template_name, context={'form': form})


class DeleteView(TemplateView):
    model = None
    template_name = None
    redirect_url = None
    object = None
    context_key = 'object'
    confirmation = True

    def get_redirect_url(self):
        return self.redirect_url

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        if self.confirmation:
            return render(request, self.template_name, context={self.context_key: self.object})
        else:
            self.object.delete()
            return redirect(self.redirect_url)

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        self.object.delete()
        return redirect(self.redirect_url)

source/webapp/views/index.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import TemplateView, ListView

from webapp.forms import SearchForm
from webapp.models import Task, Status, Type as Type


class IndexView(ListView):
    template_name = 'index.html'
    model = Task
    context_object_name = 'tasks'
    paginate_by = 6
    paginate_orphans = 1


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value.lower()) | Q(description__icontains=self.search_value.lower())
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        context['status']= Status.objects.all()
        context['types']= Type.objects.all()
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

source/webapp/views/project.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from accounts.forms import TeamAddForm
from accounts.models import Team
from webapp.forms import ProjectCreateForm, SearchForm, ProjectForm
from webapp.models import Project, PROJECT_STATUS_DEFAULT


class ProjectsView(ListView):
    template_name = 'project_templates/project_list.html'
    model = Project
    context_object_name = 'projects'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value.lower())
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        else:
            context['projects_active'] = self.model.objects.filter(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
            context['projects_closed'] = self.model.objects.exclude(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectView(DetailView):
    template_name = 'project_templates/project.html'
    model = Project
    context_key = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        tasks = project.tasks.order_by('-created_at')
        paginator = Paginator(tasks, 3, 1)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['tasks'] = page.object_list
        context['is_paginated'] = page.has_other_pages()
        context['team'] = User.objects.filter(team__project=project).filter(team__end_date=None)
        context['project_squad'] = Team.objects.filter(project=project, end_date=None).distinct()
        context['form'] = TeamAddForm(project=self.object)
        return context



class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project_templates/project_create.html'
    model = Project
    context_object_name = 'form'
    form_class = ProjectCreateForm
    permission_required = 'webapp.add_project'
    permission_denied_message = 'Проекты могут создавать только менеджеры!'

    def form_valid(self, form):
        self.object = form.save()
        print(form.cleaned_data['project_squad'])

        for user in form.cleaned_data['project_squad']:
            Team.objects.create(project=self.object, starting_date=form.cleaned_data['starting_date'], user=user)
        if self.request.user not in form.cleaned_data['project_squad']:
            Team.objects.create(project = self.object, starting_date=datetime.now(), user_id=self.request.user.id)

        return HttpResponseRedirect(self.get_success_url())


    def get_success_url(self):
        return reverse('webapp:view project', kwargs={'pk':self.object.pk})


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'project_templates/project_update.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm
    permission_required = 'webapp.change_project'
    permission_denied_message = 'Проекты могут редактировать только менеджеры!'

    def get_success_url(self):
        return reverse('webapp:view project', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project_templates/project_delete.html'
    model = Project
    success_url = '/projects/'
    permission_required = 'webapp.delete_project'
    permission_denied_message = 'Проекты могут удалять только менеджеры!'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = 'closed'
        self.object.save()
        return HttpResponseRedirect(success_url)

source/webapp/views/search.py
# from urllib.parse import urlencode
#
# from django.db.models import Q
# from django.views.generic import ListView
#
# from webapp.forms import SearchForm
# from webapp.models import PROJECT_STATUS_DEFAULT
#
#
# class SearchView(ListView):
#     filter = {'field':None , 'criteria': None}
#
#     def get(self, request, *args, **kwargs):
#         self.form = self.get_search_form()
#         self.search_value = self.get_search_value()
#         return super().get(request, *args, **kwargs)
#
#     def get_query(self):
#
#         return Q(exec(field__criteria = self.search.value in self.filter))
#
#
#     def get_queryset(self):
#         queryset = super().get_queryset()
#         if self.search_value:
#             query = self.get_query()
#             queryset = queryset.filter(query)
#         return queryset
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(object_list=object_list, **kwargs)
#         context['form'] = self.form
#         if self.search_value:
#             context['query'] = urlencode({'search': self.search_value})
#         else:
#             context['projects_active'] = self.model.objects.filter(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
#             context['projects_closed'] = self.model.objects.exclude(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
#         return context
#
#     def get_search_form(self):
#         return SearchForm(self.request.GET)
#
#     def get_search_value(self):
#         if self.form.is_valid():
#             return self.form.cleaned_data['search']
#         return None

source/webapp/views/status.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import StatusForm
from webapp.models import Status


class StatusAddView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'status_templates/status_add.html'
    success_url = '/'

    def form_valid(self, form):
        return super().form_valid(form)


class EditStatusView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status_templates/status_edit.html'
    form_class = StatusForm
    context_key = 'status'
    def get_success_url(self):
        return reverse('webapp:main_page')


class DeleteStatusView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status_templates/status_delete.html'
    context_key = 'status'
    success_url = '/'

source/webapp/templates/project_templates/project.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Просмотр задачи{% endblock %}
{% block content %}
    <div class = "d-flex flex-column pt-5 pb-5">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-12">
                <h1>Проект</h1>
                <h2><strong>Описание проекта:</strong> {{ project.name }}</h2>
                <h3><strong>Статус: </strong>{{ project.get_status_display }}</h3>
                <p><strong>Дата создания:</strong> {{ project.created_at }}</p>
                <p><strong>Дата обновления: </strong> {{ project.updated_at }}</p>
                <p><strong>Подробно:</strong> {{ project.description|escape|linebreaks }}</p>
            </div>
            <div class="col-lg-6 col-md-6 col-12 align-self-center justify-content-center d-flex">
                {% if request.user in team and perms.webapp.add_task %}
                    <a href="{% url 'webapp:create task' project.pk%}"class="btn btn-lg btn-success">Добавить задачу</a>
                {% endif %}
            </div>
        </div>


        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Член команды</th>
                <th scope="col">Дата начала работы</th>
                <th scope="col">Убрать из команды</th>
            </tr>
            </thead>
            <tbody>
            {% for member in project_squad %}
                <tr>
                    <th scope="row">{{ forloop.counter }}</th>
                    <td>
                        {% if not member.user.first_name %} }
                            {{ member.user.username }}
                        {% else %}
                            {{ member.user.first_name }}
                            {{ member.user.last_name }}
                        {% endif %}
                    </td>
                    <td>{{ member.starting_date }}</td>
                    <td><a href="{% url 'accounts:remove member from team' member.pk%}">Продать негра</a></td>
                </tr>
            {% endfor %}
            {% if perms.accounts.add_team %}
                <tr>
                    <button type="button" class="btn btn-info" data-toggle="modal" data-target="#teamAdd">Добавить пользователя</button>
                </tr>
            {% endif %}
            </tbody>
        </table>
        <div class = "btn-block mt-3 mb-3">
            {% if perms.webapp.change_project %}
                <a href="{% url  'webapp:edit project' project.pk %}" class="card-link btn btn-success btn-sm">Редактировать</a>
            {% endif %}

            {% if perms.webapp.delete_project %}
                <a href="{% url 'webapp:delete project' project.pk %}" class="card-link btn btn-success btn-sm">Удалить</a>
            {% endif %}

            <a class = "btn btn-warning" href="{% url 'webapp:main_page' %}">Вернуться на главную страницу</a>
            <a class = "btn btn-warning" href="{% url 'webapp:view projects' %}">Вернуться к списку проектов</a>
        </div>
        {% if is_paginated %}
            {% include 'partial/pagination.html' %}
        {% endif %}
        {% include 'partial/task_list.html' %}
    </div>
    {% include 'partial/modal_team_add.html' %}
{% endblock %}

source/webapp/templates/project_templates/project_create.html
{% extends 'base.html' %}
{% block title %}Создать проект{% endblock %}
{% block content %}
    <div class = "d-flex justify-content-center pt-5 pb-5">
        <form action="{% url 'webapp:create project' %}" method="POST" class = "w-50 pt-3 pb-3">
            {% include 'partial/form.html' with button_text="Создать" %}
        </form>
    </div>
{% endblock %}

source/webapp/templates/project_templates/project_delete.html
{% extends 'base.html' %}

{% block title %}Удаление проекта{% endblock %}
{% block content %}
    <div class = "d-flex flex-column justify-content-center pt-5 pb-5">
        <h1>Удаление проекта</h1>
        <h2><strong>Название проекта: </strong> {{ project.name }}</h2>
        <h5>Вы уверены, что хотите удалить данный проект?</h5>
        <form method="POST" action="{% url 'webapp:delete project' project.pk %}">
            {% csrf_token %}
            <div class = "btn-group pl-5">
                <input type="submit" class  = 'btn btn-outline-warning' value="Confirm">
                <a type="submit" class  = 'btn btn-outline-warning' href="{% url 'webapp:view project' project.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

source/webapp/templates/project_templates/project_list.html
{% extends 'base.html' %}

{% block title %}Список проектов{% endblock %}
{% block menu %}
    <a href="{% url 'webapp:main_page' %}" class="nav-link">К задачам</a>

{% endblock %}
{% block menu_buttons %}
    <a class = "nav-link" href="{% url 'webapp:create project' %}">Создать проект</a>
    <form class="form-inline my-2 my-lg-0" action="{% url 'webapp:view projects' %}" method="get">
        {% include 'partial/search_form.html' %}
    </form>
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
{% endblock %}
{% block content %}
    <h1 class = "text-center pt-3">Проекты</h1>
    <h2 class = "text-center pt-2">Активные</h2>
    {% if projects and query %}
        <div class="mt-1 mb-1 row justify-content-center">
            {% for project in projects %}
                {% include 'partial/project_card.html' %}
            {% endfor %}
        </div>
    {% else %}
        <div class="mt-1 mb-1 row justify-content-center">
            {% for project in projects_active %}
                {% include 'partial/project_card.html' %}
            {% endfor %}
        </div>
        <h2 class = "text-center pt-2">Закрытые</h2>
        {% if projects_closed %}
            <div class="mt-1 mb-1 row justify-content-center">
                {% for project in projects_closed %}
                    {% include 'partial/project_card.html' %}
                {% endfor %}
            </div>
        {% else %}
            <h3 class="text-center pt-2">Нет закрытых проектов</h3>
        {% endif %}
    {% endif %}
{% endblock %}

source/webapp/templates/project_templates/project_update.html
{% extends 'base.html' %}
{% block title %}Редактировать проект{% endblock %}
{% block content %}
    <div class = "d-flex justify-content-center pt-5 pb-5">
        <form action="{% url 'webapp:edit project' project.pk %}" method="POST" class = "w-50 pt-3 pb-3">
            {% include 'partial/form.html' with button_text="Редактировать" %}
        </form>
    </div>
{% endblock %}