source/accounts/urls.py
from django.urls import path
from accounts.views import UserLogoutView, login_view, register_view, UserDetailView, UserUpdateView, \
    UserPasswordChangeView, UserListView, TeamAddView, TeamRemoveView

urlpatterns = [
    path('login/', login_view, name='login' ),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', register_view, name='register'),
    path('<int:pk>/', UserDetailView.as_view(), name='user details'),
    path('<int:pk>/edit', UserUpdateView.as_view(), name='update user info'),
    path('<int:pk>/password', UserPasswordChangeView.as_view(), name='change user password'),
    path('users/', UserListView.as_view(), name='list users'),

    path('project/<int:pk>/team/add/', TeamAddView.as_view(), name='add team member'),
    path('project/team/remove/<int:pk>/', TeamRemoveView.as_view(), name='remove member from team')
]


app_name='accounts'

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from accounts.views import login_view, UserLogoutView
from main import settings
from webapp.views import IndexView, TaskView, CreateTaskView, EditTaskView, DeleteTaskView, StatusAddView, TypeAddView, \
    EditStatusView, DeleteStatusView, EditTypeView, DeleteTypeView, ProjectsView, ProjectView, ProjectCreateView, \
    ProjectEditView, ProjectDeleteView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('api/v1/', include('api_v1.urls')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path

from webapp.views import TaskView, CreateTaskView, EditTaskView, IndexView, DeleteTaskView, StatusAddView, \
    EditStatusView, DeleteStatusView, TypeAddView, EditTypeView, DeleteTypeView, ProjectsView, ProjectView, \
    ProjectCreateView, ProjectEditView, ProjectDeleteView

urlpatterns = [
    path('', IndexView.as_view(), name='main_page'),
    path('task/<int:pk>/', TaskView.as_view(), name='view task'),
    path('project/<int:pk>/task/create/', CreateTaskView.as_view(), name='create task'),
    path('task/<int:pk>/edit/', EditTaskView.as_view(), name='edit task'),
    path('task/<int:pk>/delete/', DeleteTaskView.as_view(), name='delete task'),

    path('status/add/', StatusAddView.as_view(), name='add status'),
    path('status/<int:pk>/edit/', EditStatusView.as_view(), name='edit status'),
    path('status/<int:pk>/delete/', DeleteStatusView.as_view(), name='delete status'),

    path('types/add/', TypeAddView.as_view(), name='add type'),
    path('types/<int:pk>/edit/', EditTypeView.as_view(), name='edit type'),
    path('types/<int:pk>/delete/', DeleteTypeView.as_view(), name='delete type'),

    path('projects/', ProjectsView.as_view(), name='view projects'),
    path('project/<int:pk>/', ProjectView.as_view(), name='view project'),
    path('project/create/', ProjectCreateView.as_view(), name='create project'),
    path('project/<int:pk>/edit/', ProjectEditView.as_view(), name='edit project'),
    path('project/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete project'),
]

app_name='webapp'

source/webapp/views/baseclass.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.views.generic import TemplateView


class DetailView(TemplateView):
    context_key = 'object'
    model = None

    def get_object(self, pk):
        try:
            some_object = self.model.objects.get(pk=pk)
        except self.model.DoesNotExist:
            raise Http404('НЕТ ТАКОГО ОБЪЕКТА!')
        return some_object

    def get_context_data(self, **kwargs):
        pk = kwargs.get('pk')
        context = super().get_context_data(**kwargs)
        context[self.context_key] = self.get_object(pk=pk)
        return context


class UpdateView(TemplateView):
    model = None
    form_class = None
    template_name = None
    redirect_url = None
    object = None
    context_key = 'object'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        form = self.form_class(instance=self.object)
        return render(request, self.template_name, context={'form': form, self.context_key: self.object})

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        form = self.form_class(instance=self.object, data=request.POST)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def get_redirect_url(self):
        return self.redirect_url

    def form_valid(self, form):
        form.save()
        return redirect(self.get_redirect_url())

    def form_invalid(self, form):
        return render(self.request, self.template_name, context={'form': form})


class DeleteView(TemplateView):
    model = None
    template_name = None
    redirect_url = None
    object = None
    context_key = 'object'
    confirmation = True

    def get_redirect_url(self):
        return self.redirect_url

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        if self.confirmation:
            return render(request, self.template_name, context={self.context_key: self.object})
        else:
            self.object.delete()
            return redirect(self.redirect_url)

    def post(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        self.object = get_object_or_404(self.model, pk=pk)
        self.object.delete()
        return redirect(self.redirect_url)

source/webapp/views/index.py
from django.db.models import Q
from django.utils.http import urlencode
from django.views.generic import TemplateView, ListView

from webapp.forms import SearchForm
from webapp.models import Task, Status, Type as Type


class IndexView(ListView):
    template_name = 'index.html'
    model = Task
    context_object_name = 'tasks'
    paginate_by = 6
    paginate_orphans = 1


    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(summary__icontains=self.search_value.lower()) | Q(description__icontains=self.search_value.lower())
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        context['status']= Status.objects.all()
        context['types']= Type.objects.all()
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

source/webapp/views/project.py
from datetime import datetime

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.http import urlencode
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from accounts.forms import TeamAddForm
from accounts.models import Team
from webapp.forms import ProjectCreateForm, SearchForm, ProjectForm
from webapp.models import Project, PROJECT_STATUS_DEFAULT


class ProjectsView(ListView):
    template_name = 'project_templates/project_list.html'
    model = Project
    context_object_name = 'projects'

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            query = Q(name__icontains=self.search_value.lower())
            queryset = queryset.filter(query)
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        else:
            context['projects_active'] = self.model.objects.filter(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
            context['projects_closed'] = self.model.objects.exclude(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
        return context

    def get_search_form(self):
        return SearchForm(self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectView(DetailView):
    template_name = 'project_templates/project.html'
    model = Project
    context_key = 'project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        project = self.object
        tasks = project.tasks.order_by('-created_at')
        paginator = Paginator(tasks, 3, 1)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['tasks'] = page.object_list
        context['is_paginated'] = page.has_other_pages()
        context['team'] = User.objects.filter(team__project=project).filter(team__end_date=None)
        context['project_squad'] = Team.objects.filter(project=project, end_date=None).distinct()
        context['form'] = TeamAddForm(project=self.object)
        return context



class ProjectCreateView(PermissionRequiredMixin, CreateView):
    template_name = 'project_templates/project_create.html'
    model = Project
    context_object_name = 'form'
    form_class = ProjectCreateForm
    permission_required = 'webapp.add_project'
    permission_denied_message = 'Проекты могут создавать только менеджеры!'

    def form_valid(self, form):
        self.object = form.save()
        print(form.cleaned_data['project_squad'])

        for user in form.cleaned_data['project_squad']:
            Team.objects.create(project=self.object, starting_date=form.cleaned_data['starting_date'], user=user)
        if self.request.user not in form.cleaned_data['project_squad']:
            Team.objects.create(project = self.object, starting_date=datetime.now(), user_id=self.request.user.id)

        return HttpResponseRedirect(self.get_success_url())


    def get_success_url(self):
        return reverse('webapp:view project', kwargs={'pk':self.object.pk})


class ProjectEditView(PermissionRequiredMixin, UpdateView):
    template_name = 'project_templates/project_update.html'
    model = Project
    context_object_name = 'project'
    form_class = ProjectForm
    permission_required = 'webapp.change_project'
    permission_denied_message = 'Проекты могут редактировать только менеджеры!'

    def get_success_url(self):
        return reverse('webapp:view project', kwargs={'pk': self.object.pk})


class ProjectDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'project_templates/project_delete.html'
    model = Project
    success_url = '/projects/'
    permission_required = 'webapp.delete_project'
    permission_denied_message = 'Проекты могут удалять только менеджеры!'

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.status = 'closed'
        self.object.save()
        return HttpResponseRedirect(success_url)

source/webapp/views/search.py
# from urllib.parse import urlencode
#
# from django.db.models import Q
# from django.views.generic import ListView
#
# from webapp.forms import SearchForm
# from webapp.models import PROJECT_STATUS_DEFAULT
#
#
# class SearchView(ListView):
#     filter = {'field':None , 'criteria': None}
#
#     def get(self, request, *args, **kwargs):
#         self.form = self.get_search_form()
#         self.search_value = self.get_search_value()
#         return super().get(request, *args, **kwargs)
#
#     def get_query(self):
#
#         return Q(exec(field__criteria = self.search.value in self.filter))
#
#
#     def get_queryset(self):
#         queryset = super().get_queryset()
#         if self.search_value:
#             query = self.get_query()
#             queryset = queryset.filter(query)
#         return queryset
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         context = super().get_context_data(object_list=object_list, **kwargs)
#         context['form'] = self.form
#         if self.search_value:
#             context['query'] = urlencode({'search': self.search_value})
#         else:
#             context['projects_active'] = self.model.objects.filter(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
#             context['projects_closed'] = self.model.objects.exclude(status=PROJECT_STATUS_DEFAULT).order_by('created_at')
#         return context
#
#     def get_search_form(self):
#         return SearchForm(self.request.GET)
#
#     def get_search_value(self):
#         if self.form.is_valid():
#             return self.form.cleaned_data['search']
#         return None

source/webapp/views/status.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import StatusForm
from webapp.models import Status


class StatusAddView(LoginRequiredMixin, CreateView):
    model = Status
    form_class = StatusForm
    template_name = 'status_templates/status_add.html'
    success_url = '/'

    def form_valid(self, form):
        return super().form_valid(form)


class EditStatusView(LoginRequiredMixin, UpdateView):
    model = Status
    template_name = 'status_templates/status_edit.html'
    form_class = StatusForm
    context_key = 'status'
    def get_success_url(self):
        return reverse('webapp:main_page')


class DeleteStatusView(LoginRequiredMixin, DeleteView):
    model = Status
    template_name = 'status_templates/status_delete.html'
    context_key = 'status'
    success_url = '/'

source/webapp/views/type.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView, DeleteView

from webapp.forms import TypeForm
from webapp.models import Type as Type


class TypeAddView(LoginRequiredMixin, CreateView):
    model = Type
    form_class = TypeForm
    template_name = 'type_templates/type_add.html'
    success_url = '/'

    def form_valid(self, form):
        return super().form_valid(form)


class EditTypeView(LoginRequiredMixin, UpdateView):
    model = Type
    template_name = 'type_templates/type_edit.html'
    success_url = '/'
    form_class = TypeForm
    context_key = 'type'


class DeleteTypeView(LoginRequiredMixin, DeleteView):
    model = Type
    template_name = 'type_templates/type_delete.html'
    context_key = 'type'
    success_url = '/'

source/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}MySite{% endblock %}</title>
    <link rel="stylesheet" href="{% static "/css/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "/css/style.css" %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">>
    <div class="collapse navbar-collapse" >
        <ul class="navbar-nav mr-auto">
            <li class="nav-item"><a href="{% url 'webapp:main_page' %}" class="nav-link">Home</a></li>
            {% block menu %}{% endblock %}
        </ul>
        {% block menu_buttons %}{% endblock %}
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src={% static "/js/jquery-3.3.1.slim.min.js"%}></script>
<script src={% static "/js/popper.min.js"%}></script>
<script src={% static "/js/bootstrap.min.js"%}></script>
<script type="application/javascript" src="{% static "js/main.js" %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

source/webapp/templates/index.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}
{% block menu %}
    <a href="{% url 'webapp:view projects' %}" class="nav-link">К проектам</a>
    <a href="{% url 'accounts:list users' %}" class="nav-link">Список холопов</a>
    {% if not request.user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'accounts:register' %}" class="nav-link">Регистрация</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:login' %}" class="nav-link">Войти в трекер</a>
        </li>
    {% else %}
        <span class="ml-3 navbar-text">Вы вошли как </span>
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarProfileDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ request.user.username }}
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarProfileDropdown">
            <a class="dropdown-item" href="{% url 'accounts:user details' request.user.pk %}">Личная страница</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:logout' %}">Покинуть трекер</a>
        </div>
    {% endif %}
{% endblock %}
{% block menu_buttons %}
    <form class="form-inline my-2 my-lg-0" action="{% url 'webapp:main_page' %}" method="get">
        {% include 'partial/search_form.html' %}
    </form>
    <div class=" btn-group btn-group-sm">
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#statuslist">Список статусов</button>
        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#typeslist">Список типов</button>
    </div>
{% endblock %}
{% block styles %}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
{% endblock %}
{% block content %}
        <h1 class = "text-center pt-3">Задачи</h1>
        {% include 'partial/pagination.html' %}
        <div class="mt-1 mb-1 row justify-content-center">
            {% for task in tasks %}
                <div class="card ml-1 mr-1 mb-1" style="width: 18rem;">
                    <div class="card-header">
                        <h5 class="card-title text-center">{{ task.summary }}</h5>
                    </div>
                    <div class="card-body ">
                        <h6><strong>Тип: </strong>{{ task.type }}</h6>
                        <h6><strong>Статус: </strong>{{ task.status }}</h6>
                        <h6><strong>Исполнитель: </strong>{{ task.assigned_to }}</h6>
                    </div>
                    <div class="btn-group">
                        <a href="{% url 'webapp:view task' task.pk %}" class="card-link btn btn-success btn-sm">Просмотр</a>
                        {% if task.project.status == 'closed' %}
                        {% else %}
                            <a href="{% url  'webapp:edit task' task.pk %}" class="card-link btn btn-success btn-sm">Редактировать</a>
                            <a href="{% url 'webapp:delete task' task.pk %}" class="card-link btn btn-success btn-sm">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
    {% include 'partial/pagination.html' %}
    {% include 'partial/modal_window_status.html' %}
    {% include 'partial/modal_window_types.html' %}
{% endblock %}

source/webapp/templates/protected_error.html
{% block title %}Ошибка!{% endblock %}
{% block content %}
    <h1>Данный элемент защищен от удаления настройками целостности базы данных!</h1>
{% endblock %}